"""Signal connectivity checker based on DOT graph connectivity.

Phase-1 goal:
- Given a source signal and destination signal, verify whether at least one path exists.
- Input graph is typically after-proc DOT generated by Yosys show.
"""

from dataclasses import dataclass, field
from collections import deque, defaultdict
from typing import Dict, List, Optional, Set

from schematic.simplifier import DotParser


@dataclass
class ConnectivityResult:
    """Connectivity check result for one signal pair."""

    module_name: str
    from_signal: str
    to_signal: str
    directed: bool
    exists: bool
    matched_from_nodes: List[str] = field(default_factory=list)
    matched_to_nodes: List[str] = field(default_factory=list)
    path_nodes: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, object]:
        """Convert result to serializable dict."""
        return {
            "module": self.module_name,
            "from_signal": self.from_signal,
            "to_signal": self.to_signal,
            "directed": self.directed,
            "exists": self.exists,
            "matched_from_nodes": self.matched_from_nodes,
            "matched_to_nodes": self.matched_to_nodes,
            "path_nodes": self.path_nodes,
        }


class ConnectivityChecker:
    """Graph connectivity checker for DOT schematics."""

    def __init__(self, verbose: bool = False):
        self._verbose = verbose

    def check_connectivity(
        self,
        dot_content: str,
        from_signal: str,
        to_signal: str,
        module_name: str = "",
        directed: bool = True,
    ) -> ConnectivityResult:
        """Check if a path exists from `from_signal` to `to_signal`.

        Args:
            dot_content: DOT graph content.
            from_signal: Source signal label.
            to_signal: Destination signal label.
            module_name: Optional module name for reporting.
            directed: Use directed edges if True, otherwise treat as undirected.

        Returns:
            ConnectivityResult with existence and one witness path when reachable.
        """
        parser = DotParser()
        parser.parse(dot_content)

        from_nodes = self.find_signal_nodes(parser, from_signal)
        to_nodes = self.find_signal_nodes(parser, to_signal)

        if self._verbose:
            print(f"[connectivity] from '{from_signal}' matched nodes: {from_nodes}")
            print(f"[connectivity] to   '{to_signal}' matched nodes: {to_nodes}")

        if not from_nodes or not to_nodes:
            return ConnectivityResult(
                module_name=module_name,
                from_signal=from_signal,
                to_signal=to_signal,
                directed=directed,
                exists=False,
                matched_from_nodes=from_nodes,
                matched_to_nodes=to_nodes,
                path_nodes=[]
            )

        adjacency = self._build_adjacency(parser, directed=directed)
        path = self._find_first_path(adjacency, from_nodes, set(to_nodes))

        return ConnectivityResult(
            module_name=module_name,
            from_signal=from_signal,
            to_signal=to_signal,
            directed=directed,
            exists=bool(path),
            matched_from_nodes=from_nodes,
            matched_to_nodes=to_nodes,
            path_nodes=path or []
        )

    def find_signal_nodes(self, parser: DotParser, signal_name: str) -> List[str]:
        """Find DOT node IDs whose label exactly matches given signal name."""
        normalized_signal = self._normalize_signal(signal_name)
        matched_nodes: List[str] = []

        for node_id, node in parser.nodes.items():
            node_label = self._normalize_signal(node.label)
            if node_label == normalized_signal:
                matched_nodes.append(node_id)

        return matched_nodes

    def _build_adjacency(self, parser: DotParser, directed: bool) -> Dict[str, Set[str]]:
        """Build adjacency list from parsed DOT edges."""
        adjacency: Dict[str, Set[str]] = defaultdict(set)

        for edge in parser.edges:
            adjacency[edge.src_node].add(edge.dst_node)
            if not directed:
                adjacency[edge.dst_node].add(edge.src_node)

        return adjacency

    def _find_first_path(
        self,
        adjacency: Dict[str, Set[str]],
        source_nodes: List[str],
        target_nodes: Set[str]
    ) -> Optional[List[str]]:
        """Find first reachable path using multi-source BFS."""
        queue = deque()
        parent: Dict[str, Optional[str]] = {}

        for src in source_nodes:
            if src in target_nodes:
                return [src]
            queue.append(src)
            parent[src] = None

        while queue:
            current = queue.popleft()

            for nxt in adjacency.get(current, set()):
                if nxt in parent:
                    continue

                parent[nxt] = current

                if nxt in target_nodes:
                    return self._reconstruct_path(parent, nxt)

                queue.append(nxt)

        return None

    def _reconstruct_path(
        self,
        parent: Dict[str, Optional[str]],
        end_node: str
    ) -> List[str]:
        """Reconstruct node path from parent map."""
        path: List[str] = []
        cur: Optional[str] = end_node

        while cur is not None:
            path.append(cur)
            cur = parent.get(cur)

        path.reverse()
        return path

    def _normalize_signal(self, signal_name: str) -> str:
        """Normalize signal text for strict matching."""
        if signal_name is None:
            return ""

        text = signal_name.strip()
        if text.startswith("\\"):
            text = text[1:]

        return text
