"""Signal connectivity checker based on DOT graph connectivity.

Phase-1 goal:
- Given a source signal and destination signal, verify whether at least one path exists.
- Input graph is typically after-proc DOT generated by Yosys show.
"""

from dataclasses import dataclass, field
from collections import deque, defaultdict
from typing import Dict, List, Optional, Set, Tuple
import re
import sys

from schematic.simplifier import DotParser, DotEdge
from models import SourceLocation


@dataclass
class ConnectivityResult:
    """Connectivity check result for one signal pair."""

    module_name: str
    from_signal: str
    to_signal: str
    directed: bool
    exists: bool
    matched_from_nodes: List[str] = field(default_factory=list)
    matched_to_nodes: List[str] = field(default_factory=list)
    path_nodes: List[str] = field(default_factory=list)
    all_path_nodes: List[List[str]] = field(default_factory=list)
    path_count: int = 0
    truncated: bool = False
    has_conditions: bool = False
    conditions: List[Dict[str, object]] = field(default_factory=list)
    path_conditions: List[Dict[str, object]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, object]:
        """Convert result to serializable dict."""
        return {
            "module": self.module_name,
            "from_signal": self.from_signal,
            "to_signal": self.to_signal,
            "directed": self.directed,
            "exists": self.exists,
            "matched_from_nodes": self.matched_from_nodes,
            "matched_to_nodes": self.matched_to_nodes,
            "path_nodes": self.path_nodes,
            "all_path_nodes": self.all_path_nodes,
            "path_count": self.path_count,
            "truncated": self.truncated,
            "has_conditions": self.has_conditions,
            "conditions": self.conditions,
            "path_conditions": self.path_conditions,
        }


class ConnectivityChecker:
    """Graph connectivity checker for DOT schematics."""

    def __init__(self, verbose: bool = False):
        self._verbose = verbose
        self._sequential_conditional_types = {
            "$dff", "$adff", "$sdff", "$sdffe", "$dffe", "$dffsre", "$dlatch"
        }
        self._mux_types = {"$mux", "$pmux", "$procmux"}
        self._mux_select_port_names = {"S", "SEL", "S0", "S1", "S2", "S3", "S4"}
        self._sequential_condition_port_names = {
            "EN", "CE", "LOAD", "GATE"
        }
        self._sequential_control_port_names = {
            "CLK", "ARST", "SRST", "RST", "RESET", "SET", "CLR", "EN", "CE", "LOAD", "GATE"
        }

    def check_connectivity(
        self,
        dot_content: str,
        from_signal: str,
        to_signal: str,
        module_name: str = "",
        directed: bool = True,
        cell_locations: Optional[Dict[str, SourceLocation]] = None,
        max_paths: int = 0,
        max_depth: int = 0,
    ) -> ConnectivityResult:
        """Check if a path exists from `from_signal` to `to_signal`.

        Args:
            dot_content: DOT graph content.
            from_signal: Source signal label.
            to_signal: Destination signal label.
            module_name: Optional module name for reporting.
            directed: Use directed edges if True, otherwise treat as undirected.

        Returns:
            ConnectivityResult with existence and one witness path when reachable.
        """
        parser = DotParser()
        parser.parse(dot_content)

        from_nodes = self.find_signal_nodes(parser, from_signal)
        to_nodes = self.find_signal_nodes(parser, to_signal)

        if self._verbose:
            print(f"[connectivity] from '{from_signal}' matched nodes: {from_nodes}")
            print(f"[connectivity] to   '{to_signal}' matched nodes: {to_nodes}")

        if not from_nodes or not to_nodes:
            return ConnectivityResult(
                module_name=module_name,
                from_signal=from_signal,
                to_signal=to_signal,
                directed=directed,
                exists=False,
                matched_from_nodes=from_nodes,
                matched_to_nodes=to_nodes,
                path_nodes=[],
                all_path_nodes=[],
                path_count=0,
                truncated=False,
            )

        adjacency = self._build_adjacency(parser, directed=directed)
        all_paths, truncated = self._find_all_simple_paths(
            adjacency,
            from_nodes,
            set(to_nodes),
            max_paths=max_paths,
            max_depth=max_depth,
        )

        path = all_paths[0] if all_paths else None

        path_conditions: List[Dict[str, object]] = []
        all_conditions: List[Dict[str, object]] = []
        for index, one_path in enumerate(all_paths):
            one_conditions = self._extract_path_conditions(parser, one_path)
            if cell_locations:
                one_conditions = self._attach_source_locations(one_conditions, cell_locations)

            path_conditions.append({
                "path_index": index,
                "path_nodes": one_path,
                "conditions": one_conditions,
            })
            all_conditions.extend(one_conditions)

        conditions = self._dedup_conditions(all_conditions)

        return ConnectivityResult(
            module_name=module_name,
            from_signal=from_signal,
            to_signal=to_signal,
            directed=directed,
            exists=bool(all_paths),
            matched_from_nodes=from_nodes,
            matched_to_nodes=to_nodes,
            path_nodes=path or [],
            all_path_nodes=all_paths,
            path_count=len(all_paths),
            truncated=truncated,
            has_conditions=bool(conditions),
            conditions=conditions,
            path_conditions=path_conditions,
        )

    def find_signal_nodes(self, parser: DotParser, signal_name: str) -> List[str]:
        """Find DOT node IDs whose label exactly matches given signal name."""
        normalized_signal = self._normalize_signal(signal_name)
        matched_nodes: List[str] = []

        for node_id, node in parser.nodes.items():
            node_label = self._normalize_signal(node.label)
            if node_label == normalized_signal:
                matched_nodes.append(node_id)

        return matched_nodes

    def _build_adjacency(self, parser: DotParser, directed: bool) -> Dict[str, Set[str]]:
        """Build adjacency list from parsed DOT edges."""
        adjacency: Dict[str, Set[str]] = defaultdict(set)

        port_name_maps: Dict[str, Dict[str, str]] = {}
        cell_types: Dict[str, str] = {}
        for node_id, node in parser.nodes.items():
            cell_types[node_id] = self._extract_cell_type(node.label)
            port_name_maps[node_id] = self._extract_port_name_map(node.label)

        for edge in parser.edges:
            if self._is_control_only_edge(edge, cell_types, port_name_maps):
                continue

            adjacency[edge.src_node].add(edge.dst_node)
            if not directed:
                adjacency[edge.dst_node].add(edge.src_node)

        return adjacency

    def _is_control_only_edge(
        self,
        edge: DotEdge,
        cell_types: Dict[str, str],
        port_name_maps: Dict[str, Dict[str, str]],
    ) -> bool:
        """Return True when an edge carries control-only dependency (not data flow).

        Current rule: skip edges driving MUX select ports so connectivity search
        focuses on data propagation path.
        """
        dst_cell_type = cell_types.get(edge.dst_node, "")
        dst_port_id = self._normalize_port_id(edge.dst_port)
        if not dst_port_id:
            return False

        port_name_map = port_name_maps.get(edge.dst_node, {})
        dst_port_name = port_name_map.get(dst_port_id, dst_port_id).upper()

        if dst_cell_type in self._mux_types:
            if self._is_select_port_name(dst_port_name):
                return True

        if dst_cell_type in self._sequential_conditional_types:
            if self._is_sequential_control_port_name(dst_port_name):
                return True

        return False

    def _is_select_port_name(self, port_name: str) -> bool:
        """Return True if port name looks like a mux select pin."""
        if not port_name:
            return False
        if port_name in self._mux_select_port_names:
            return True
        return bool(re.match(r"^(S|SEL)\d+(\[\d+\])?$", port_name))

    def _is_sequential_control_port_name(self, port_name: str) -> bool:
        """Return True if port name is a sequential control pin (non-data)."""
        if not port_name:
            return False
        base = re.sub(r'\[\d+\]$', '', port_name)
        return base in self._sequential_control_port_names

    def _find_first_path(
        self,
        adjacency: Dict[str, Set[str]],
        source_nodes: List[str],
        target_nodes: Set[str]
    ) -> Optional[List[str]]:
        """Find first reachable path using multi-source BFS."""
        queue = deque()
        parent: Dict[str, Optional[str]] = {}

        for src in source_nodes:
            if src in target_nodes:
                return [src]
            queue.append(src)
            parent[src] = None

        while queue:
            current = queue.popleft()

            for nxt in adjacency.get(current, set()):
                if nxt in parent:
                    continue

                parent[nxt] = current

                if nxt in target_nodes:
                    return self._reconstruct_path(parent, nxt)

                queue.append(nxt)

        return None

    def _find_all_simple_paths(
        self,
        adjacency: Dict[str, Set[str]],
        source_nodes: List[str],
        target_nodes: Set[str],
        max_paths: int = 0,
        max_depth: int = 0,
    ) -> Tuple[List[List[str]], bool]:
        """Enumerate all simple paths from any source to any target.

        Args:
            adjacency: Directed or undirected adjacency set.
            source_nodes: Start node candidates.
            target_nodes: Target node set.
            max_paths: Hard cap for returned path count. 0 means unlimited.
            max_depth: Hard cap for node count in each path. 0 means unlimited.

        Returns:
            Tuple of (all paths, truncated flag).
        """
        all_paths: List[List[str]] = []
        truncated = False

        unique_sources: List[str] = []
        seen_sources: Set[str] = set()
        for source in source_nodes:
            if source in seen_sources:
                continue
            seen_sources.add(source)
            unique_sources.append(source)

        for source in unique_sources:
            if max_paths > 0 and len(all_paths) >= max_paths:
                truncated = True
                break

            if source in target_nodes:
                all_paths.append([source])
                if max_paths > 0 and len(all_paths) >= max_paths:
                    truncated = True
                    break

            initial_neighbors = iter(sorted(adjacency.get(source, set())))
            stack: List[Tuple[str, List[str], Set[str], object]] = [
                (source, [source], {source}, initial_neighbors)
            ]

            while stack:
                if max_paths > 0 and len(all_paths) >= max_paths:
                    truncated = True
                    stack.clear()
                    break

                current_node, current_path, visited_nodes, neighbors_iter = stack[-1]

                try:
                    next_node = next(neighbors_iter)
                except StopIteration:
                    stack.pop()
                    continue

                if next_node in visited_nodes:
                    continue

                next_path = current_path + [next_node]
                if max_depth > 0 and len(next_path) > max_depth:
                    continue

                if next_node in target_nodes:
                    all_paths.append(next_path)
                    continue

                next_neighbors = iter(sorted(adjacency.get(next_node, set())))
                stack.append((next_node, next_path, visited_nodes | {next_node}, next_neighbors))

        return all_paths, truncated

    def _reconstruct_path(
        self,
        parent: Dict[str, Optional[str]],
        end_node: str
    ) -> List[str]:
        """Reconstruct node path from parent map."""
        path: List[str] = []
        cur: Optional[str] = end_node

        while cur is not None:
            path.append(cur)
            cur = parent.get(cur)

        path.reverse()
        return path

    def _normalize_signal(self, signal_name: str) -> str:
        """Normalize signal text for strict matching."""
        if signal_name is None:
            return ""

        text = signal_name.strip()
        if text.startswith("\\"):
            text = text[1:]

        return text

    def _extract_path_conditions(self, parser: DotParser, path_nodes: List[str]) -> List[Dict[str, object]]:
        """Extract conditional propagation points on a resolved path."""
        if not path_nodes:
            return []

        incoming_edges: Dict[str, List[DotEdge]] = defaultdict(list)
        for edge in parser.edges:
            incoming_edges[edge.dst_node].append(edge)

        conditions: List[Dict[str, object]] = []
        warned_cell_types: Set[str] = set()

        for node_id in path_nodes:
            node = parser.nodes.get(node_id)
            if not node:
                continue

            cell_type = self._extract_cell_type(node.label)
            if not cell_type:
                continue

            port_name_map = self._extract_port_name_map(node.label)

            if cell_type in self._mux_types:
                condition_ports = self._find_ports_by_names(port_name_map, self._mux_select_port_names)
                point = self._build_condition_point(
                    parser=parser,
                    node_id=node_id,
                    cell_type=cell_type,
                    kind="mux_select",
                    condition_port_ids=condition_ports,
                    incoming_edges=incoming_edges,
                    port_name_map=port_name_map,
                )
                conditions.append(point)
                continue

            if cell_type in self._sequential_conditional_types:
                condition_ports = self._find_ports_by_names(
                    port_name_map,
                    self._sequential_condition_port_names
                )
                if condition_ports:
                    point = self._build_condition_point(
                        parser=parser,
                        node_id=node_id,
                        cell_type=cell_type,
                        kind="sequential_condition",
                        condition_port_ids=condition_ports,
                        incoming_edges=incoming_edges,
                        port_name_map=port_name_map,
                    )
                    conditions.append(point)

            if self._is_unknown_candidate_conditional_cell(cell_type):
                if cell_type not in warned_cell_types:
                    print(
                        f"[WARN] connectivity: unknown conditional-like cell type '{cell_type}' encountered on path at node {node_id}",
                        file=sys.stderr,
                    )
                    warned_cell_types.add(cell_type)

        return conditions

    def _is_unknown_candidate_conditional_cell(self, cell_type: str) -> bool:
        """Heuristic detection for conditional-like cells not in whitelist."""
        if not cell_type:
            return False
        if cell_type in self._mux_types or cell_type in self._sequential_conditional_types:
            return False

        token = cell_type.lower()
        keywords = ("mux", "dff", "ff", "latch", "flop")
        return any(keyword in token for keyword in keywords)

    def _extract_cell_type(self, label: str) -> str:
        """Extract cell type token like $mux/$adff from record label."""
        if not label:
            return ""
        match = re.search(r'\\n(\$[A-Za-z0-9_]+)\|', label)
        if match:
            return match.group(1)
        return ""

    def _extract_port_name_map(self, label: str) -> Dict[str, str]:
        """Map port id (pNNN) -> logical port name (A/B/S/CLK/ARST/...)."""
        port_map: Dict[str, str] = {}
        if not label:
            return port_map

        for match in re.finditer(r'<([^>]+)>\s*([^|{}]+)', label):
            port_id = match.group(1).strip()
            port_name = match.group(2).strip()
            if port_id:
                port_map[port_id] = port_name

        return port_map

    def _find_ports_by_names(self, port_name_map: Dict[str, str], names: Set[str]) -> List[str]:
        result: List[str] = []
        upper_names = {name.upper() for name in names}
        for port_id, port_name in port_name_map.items():
            if port_name.upper() in upper_names:
                result.append(port_id)
        return sorted(result)

    def _build_condition_point(
        self,
        parser: DotParser,
        node_id: str,
        cell_type: str,
        kind: str,
        condition_port_ids: List[str],
        incoming_edges: Dict[str, List[DotEdge]],
        port_name_map: Dict[str, str],
    ) -> Dict[str, object]:
        condition_inputs: List[Dict[str, str]] = []

        cond_port_id_set = set(condition_port_ids)
        for edge in incoming_edges.get(node_id, []):
            dst_port = self._normalize_port_id(edge.dst_port)
            if dst_port not in cond_port_id_set:
                continue

            src_node = parser.nodes.get(edge.src_node)
            signal_name = self._node_signal_name(src_node, edge.src_node)
            condition_inputs.append({
                "port_id": dst_port,
                "port_name": port_name_map.get(dst_port, dst_port),
                "source_node": edge.src_node,
                "source_signal": signal_name,
            })

        condition_ports = [port_name_map.get(port_id, port_id) for port_id in condition_port_ids]
        return {
            "node_id": node_id,
            "node_label": self._node_signal_name(parser.nodes.get(node_id), node_id),
            "cell_type": cell_type,
            "kind": kind,
            "condition_ports": condition_ports,
            "condition_inputs": condition_inputs,
        }

    def _attach_source_locations(
        self,
        conditions: List[Dict[str, object]],
        cell_locations: Dict[str, SourceLocation]
    ) -> List[Dict[str, object]]:
        """Attach source RTL locations to each condition point when available."""
        for condition in conditions:
            node_label = str(condition.get("node_label", ""))
            cell_id = self._extract_cell_id_from_label(node_label)
            if not cell_id:
                continue

            location = cell_locations.get(cell_id)
            if location:
                condition["source_locations"] = [location.to_dict()]

        return conditions

    def _extract_cell_id_from_label(self, label: str) -> str:
        """Extract numeric cell id from DOT record label such as '$94320\\n$adff'."""
        if not label:
            return ""

        match = re.search(r'\$(\d+)\\n\$', label)
        if match:
            return match.group(1)

        return ""

    def _node_signal_name(self, node, default_node_id: str) -> str:
        """Best-effort readable node name for reporting."""
        if not node:
            return default_node_id

        label = self._normalize_signal(getattr(node, "label", ""))
        if label:
            return label

        return default_node_id

    def _normalize_port_id(self, port_text: str) -> str:
        """Normalize DOT port text like 'p703:w' into canonical port id 'p703'."""
        if not port_text:
            return ""
        return port_text.split(':', 1)[0]

    def _dedup_conditions(self, conditions: List[Dict[str, object]]) -> List[Dict[str, object]]:
        """Remove duplicate condition points while preserving order."""
        deduped: List[Dict[str, object]] = []
        seen_keys: Set[str] = set()

        for condition in conditions:
            node_id = str(condition.get("node_id", ""))
            kind = str(condition.get("kind", ""))
            cell_type = str(condition.get("cell_type", ""))
            condition_ports = condition.get("condition_ports", [])
            if isinstance(condition_ports, list):
                ports_key = ",".join(str(item) for item in condition_ports)
            else:
                ports_key = str(condition_ports)

            key = f"{node_id}|{kind}|{cell_type}|{ports_key}"
            if key in seen_keys:
                continue

            seen_keys.add(key)
            deduped.append(condition)

        return deduped
